In [1]:
#1 Import NumPy

import numpy as np

In [2]:
#2

a = np.array([10, 20, 30, 40, 50])

print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
#3 One-Dimensional and Two-Dimensional Arrays

arr1 = np.array([1,2,3,4])

arr2 = np.array([[1,2],
                 [3,4]])

print("1D Array:\n",arr1)
print("2D Array:\n",arr2)

1D Array:
 [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]


In [5]:
#4 Array Properties

print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

2
(2, 2)
4
int64


In [7]:
#5 Special Arrays

print(np.zeros((2,3)))

print("\n",np.ones((3,3)))

print("\n",np.eye(4))

[[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
#6 Range Functions

print(np.arange(1,11))

print("\n",np.linspace(0,1,5))

[ 1  2  3  4  5  6  7  8  9 10]

 [0.   0.25 0.5  0.75 1.  ]


In [10]:
#7 Array Indexing

a = np.array([10,20,30,40,50])

print(a[0])
print(a[-1])

10
50


In [11]:
#8 Array Slicing

print(a[1:4])

print(a[:3])

print(a[::2])

[20 30 40]
[10 20 30]
[10 30 50]


In [12]:
#9 Mathematical Operations

a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

print(a-b)

print(a*b)

print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [13]:
#10 Universal Functions

a = np.array([1,4,9,16])

print(np.sqrt(a))

print(np.square(a))

print(np.sin(a))

[1. 2. 3. 4.]
[  1  16  81 256]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [14]:
#11 Statistical Functions

a = np.array([10,20,30,40,50])

print(np.mean(a))

print(np.median(a))

print(np.max(a))

print(np.min(a))

print(np.sum(a))

print(np.std(a))

30.0
30.0
50
10
150
14.142135623730951


In [15]:
#12 Reshape

a = np.arange(12)

print(a)

print(a.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
#13 Flatten

a = np.array([[1,2],[3,4]])

print(a.flatten())

[1 2 3 4]


In [17]:
#14 Concatenate Arrays

a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [19]:
#15 Stack Arrays

a = np.array([1,2])

b = np.array([3,4])

print(np.vstack((a,b)))

print("\n",np.hstack((a,b)))

[[1 2]
 [3 4]]

 [1 2 3 4]


In [20]:
#16 Boolean Filtering

a = np.array([5,10,15,20,25])

print(a[a>15])

[20 25]


In [21]:
#17 Copy vs View

a = np.array([1,2,3])

b = a.copy()

b[0] = 100

print(a)

print(b)

[1 2 3]
[100   2   3]


In [22]:
#18 Random Numbers

print(np.random.rand(3))

print(np.random.randint(1,100,5))

[0.10921525 0.64888489 0.9491624 ]
[97 51 78 81 97]


In [23]:
#19 Save and Load Arrays

a = np.array([10,20,30])

np.save("sample.npy",a)

b = np.load("sample.npy")

print(b)

[10 20 30]


End Summary:
-----------

Topics Covered :-

✔ Import NumPy
✔ Array Creation
✔ 1D Arrays
✔ 2D Arrays
✔ Array Properties
✔ Zeros
✔ Ones
✔ Identity Matrix
✔ Arange
✔ Linspace
✔ Indexing
✔ Slicing
✔ Mathematical Operations
✔ Universal Functions
✔ Statistics
✔ Reshape
✔ Flatten
✔ Concatenate
✔ Stack
✔ Boolean Filtering
✔ Copy vs View
✔ Random Numbers
✔ Save and Load Arrays